portfolio_portfolio_homepage:
    pattern:  /
    defaults: { _controller: PortfolioPortfolioBundle:Pages:index }

portfolio_portfolio_gmap:
    pattern:  /result/{longitude}/{latitude}
    defaults: { _controller: PortfolioPortfolioBundle:Pages:gmap }
